server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hseDB
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  freemarker:
    template-loader-path: classpath:/static/pages/templates
    suffix: .ftl

mybatis:
  type-aliases-package: com.lzq.hse.pojo


#数据库日志级别设置

logging:
  level:
    com.lzq.hse.mapper: trace
